=== dwebb34/ClassGenie/xsd/project_grammar.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 4 U (http://www.xmlspy.com) by Wm. Jaye Bass (Torch Technologies) -->
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="build_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="cmake"/>
			<xs:enumeration value="ant"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="language">
		<xs:restriction base="xs:string">
			<xs:enumeration value="c++"/>
			<xs:enumeration value="java"/>
			<xs:enumeration value="python"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="operator">
		<xs:restriction base="xs:string">
			<xs:enumeration value="assignment"/>
			<xs:enumeration value="equals"/>
			<xs:enumeration value="not_equals"/>
			<xs:enumeration value="output_stream"/>
			<xs:enumeration value="input_stream"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="types">
		<xs:restriction base="xs:string">
			<xs:enumeration value="boolean"/>
			<xs:enumeration value="int"/>
			<xs:enumeration value="short"/>
			<xs:enumeration value="unsigned short"/>
			<xs:enumeration value="long"/>
			<xs:enumeration value="unsigned long"/>
			<xs:enumeration value="float"/>
			<xs:enumeration value="double"/>
			<xs:enumeration value="long double"/>
			<xs:enumeration value="character"/>
			<xs:enumeration value="c_string"/>
			<xs:enumeration value="std_string"/>
			<xs:enumeration value="user_object"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="scope">
		<xs:restriction base="xs:string">
			<xs:enumeration value="private"/>
			<xs:enumeration value="protected"/>
			<xs:enumeration value="public"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="project">
		<xs:complexType>
			<xs:sequence>
				<xs:sequence maxOccurs="unbounded">
					<xs:element name="class">
						<xs:complexType>
							<xs:sequence minOccurs="0" maxOccurs="unbounded">
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="member_variable">
										<xs:complexType>
											<xs:attribute name="scope" type="scope" use="required"/>
											<xs:attribute name="name" type="xs:string" use="required"/>
											<xs:attribute name="type" type="types" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="operator">
										<xs:complexType>
											<xs:attribute name="type" type="operator" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="base_class">
										<xs:complexType>
											<xs:attribute name="implementation_template" type="xs:string" use="optional"/>
											<xs:attribute name="definition_template" type="xs:string" use="optional"/>
											<xs:attribute name="namespace" type="xs:string" use="optional"/>
											<xs:attribute name="name" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:sequence minOccurs="0" maxOccurs="unbounded">
									<xs:element name="function">
										<xs:complexType>
											<xs:attribute name="scope" type="scope" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:sequence>
							<xs:attribute name="name" type="xs:string" use="required"/>
							<xs:attribute name="file_name" type="xs:string" use="optional"/>
							<xs:attribute name="output_directory" type="xs:string" use="optional"/>
							<xs:attribute name="license" type="xs:string" use="optional"/>
							<xs:attribute name="definition_template" type="xs:string" use="required"/>
							<xs:attribute name="implementation_template" type="xs:string" use="optional"/>
							<xs:attribute name="language" type="language" use="required"/>
							<xs:attribute name="namespace" type="xs:string" use="optional"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:element name="build_file">
					<xs:complexType>
						<xs:attribute name="build_type" type="build_type" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="optional"/>
			<xs:attribute name="parent_directory" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dwebb34/ClassGenie/xml/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/project_grammar.xsd"
parent_directory="../examples"
name="TestGenieProject">
    <class 
        license="license.txt"
        name="ExampleClass" 
        definition_template="definition.template" 
        implementation_template="impl.template" 
        namespace="test" 
        language="c++"
        output_directory="">
        
        <!-- opeartors -->
        <operator type="assignment" />
        <operator type="equals"/>
        <operator type="not_equals"/>

        <!-- private members -->
        <member_variable type="int" name="exampleInt" scope="private"/>
        <member_variable type="c_string" name="exampleCString"  scope="private"/>
        <member_variable type="std_string" name="exampleStdString"  scope="private"/>
        
        <!-- public functions -->
        <function scope="public" />
    </class>
    <class 
        name="ExampleInheritance" 
        definition_template="definition.template" 
        implementation_template="impl.template" 
        namespace="test" 
        language="c++" >
    
        <!-- optionals -->
        <operator type="assignment" />

        <!-- member variables -->
        <member_variable type="int" name="exampleInt" scope="private"/>
        <member_variable type="c_string" name="exampleCString" scope="private"/>
        <member_variable type="std_string" name="exampleStdString" scope="private"/>
        
        <!-- base class -->
        <base_class definition_template="baseDefinition.template" implementation_template="baseImpl.template" name="Object" namespace="std"/>
        
        <!-- private functions -->
        <function scope="private" />
    </class>
    <build_file build_type="cmake"/>
</project>
